stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: extras/docker/Dockerfile
      buildContext: .
      tag: fiware-idm:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      event: {}
  when:
    event:
      include:
      - pull_request
      - push
      - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: extras/docker/keyrock-deployment.yaml
  - applyYamlConfig:
      path: extras/docker/keyrock-service.yaml
  when:
    event:
      include:
      - pull_request
      - push
      - tag
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        print "HI"
        #sys.exit(1)
timeout: 300
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-4927h
  condition:
  - Success
  - Changed
  - Failed
