stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: extras/docker/Dockerfile
      buildContext: .
      tag: fiware-idm:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      event: {}
  when:
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: extras/docker/keyrock-deployment.yaml
  - applyYamlConfig:
      path: extras/docker/keyrock-service.yaml
  when:
    event: {}
timeout: 300
notification: {}
